[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npm run build", "ls -la", "ls -la dist"]

[start]
cmd = "node dist/server.js"

[variables]
NPM_CONFIG_PRODUCTION = "false"
